// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfpeaeeshgwlmchixhbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmcGVhZWVzaGd3bG1jaGl4aGJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTg0ODEsImV4cCI6MjA2MTE3NDQ4MX0.uE2rSJIExKYPCMvTCmiTzE6k_fbA0mRtggD_UGD20L4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);